<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<PackageReference Include="MediatR" />
		<PackageReference Include="Swashbuckle.AspNetCore" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
		<PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
	</ItemGroup>

</Project>
