<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<PackageReference Include="Polly" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\TaskFlow.Shared.Core\TaskFlow.Shared.Core.csproj" />

		<ProjectReference Include="..\..\Services\Identity\TaskFlow.Identity.Contracts\TaskFlow.Identity.Contracts.csproj" />
	</ItemGroup>

</Project>
