<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<PackageReference Include="MediatR" />
		<PackageReference Include="RabbitMQ.Client" />
		<PackageReference Include="Microsoft.Extensions.Options" />
		<PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\TaskFlow.Shared.Logging\TaskFlow.Shared.Logging.csproj" />
	</ItemGroup>

</Project>
