<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="NLog" Version="6.0.7" />
    <PackageVersion Include="NLog.Web.AspNetCore" Version="6.1.0" />
    <PackageVersion Include="NLog.Extensions.Logging" Version="6.1.0" />
    <PackageVersion Include="Ocelot" Version="24.1.0" />
    <PackageVersion Include="Ocelot.Provider.Consul" Version="24.1.0" />
    <PackageVersion Include="Consul" Version="1.7.14.10" />
    <PackageVersion Include="Winton.Extensions.Configuration.Consul" Version="3.4.0" />
    <PackageVersion Include="MediatR" Version="14.0.0" />
    <PackageVersion Include="MediatR.Contracts" Version="2.0.1" />
    <PackageVersion Include="AutoMapper" Version="13.0.1" />
    <PackageVersion Include="Polly" Version="8.6.5" />
    <PackageVersion Include="RabbitMQ.Client" Version="7.2.0" />
    <PackageVersion Include="Swashbuckle.AspNetCore" Version="10.0.1" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore" Version="10.0.1" />
    <PackageVersion Include="Microsoft.AspNetCore.Http" Version="2.3.9" />
    <PackageVersion Include="Microsoft.AspNetCore.Identity" Version="2.3.1" />
    <PackageVersion Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.1" />
    <PackageVersion Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.1" />
    <PackageVersion Include="Microsoft.Extensions.Options" Version="10.0.1" />
    <PackageVersion Include="Microsoft.Extensions.Identity.Core" Version="10.0.1" />
    <PackageVersion Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.1" />
    <PackageVersion Include="Microsoft.Extensions.Diagnostics.HealthChecks" Version="10.0.1" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.1" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.1" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.1" />
  </ItemGroup>
</Project>