<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<PackageReference Include="MediatR" />
		<PackageReference Include="AutoMapper" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\TaskFlow.Tasks.Domain\TaskFlow.Tasks.Domain.csproj" />
		<ProjectReference Include="..\TaskFlow.Tasks.Contracts\TaskFlow.Tasks.Contracts.csproj" />
		<ProjectReference Include="..\TaskFlow.Tasks.Infrastructure.SqlServer\TaskFlow.Tasks.Infrastructure.SqlServer.csproj" />
		
		<ProjectReference Include="..\..\Identity\TaskFlow.Identity.Contracts\TaskFlow.Identity.Contracts.csproj" />
	</ItemGroup>

</Project>
