<Project Sdk="Microsoft.NET.Sdk.Web">

	<ItemGroup>
		<PackageReference Include="Ocelot" />
		<PackageReference Include="NLog" />
		<PackageReference Include="NLog.Web.AspNetCore" />
		<PackageReference Include="NLog.Extensions.Logging" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
		<PackageReference Include="Ocelot.Provider.Consul" />
	</ItemGroup>

	<ItemGroup>
		<Content Remove="ocelot.global.json" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Shared\TaskFlow.Shared.Consul\TaskFlow.Shared.Consul.csproj" />
		<ProjectReference Include="..\..\Shared\TaskFlow.Shared.Logging\TaskFlow.Shared.Logging.csproj" />
	</ItemGroup>

	<PropertyGroup>
		<NoWarn>ASP0014</NoWarn>
	</PropertyGroup>

</Project>
