version: '3.8'
name: TaskFlow

networks:
  taskflow-internal-network:
    driver: bridge

services:
  sqlserver:  
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: taskflow-sqlserver
    hostname: sqlserver

    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SQL_SERVER_PASSWORD}
      - MSSQL_PID=Developer

    ports:
      - "1433:1433"
  
    volumes:
      - sqlserver-data:/var/opt/mssql

    networks:
      - taskflow-internal-network

    healthcheck:
      test: ["CMD-SHELL", "timeout 10 bash -c 'cat < /dev/null > /dev/tcp/localhost/1433' || exit 1"]
      interval: 10s  
      timeout: 3s    
      retries: 10    
      start_period: 30s  
    restart: unless-stopped
  #---------------------------------------#

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: taskflow-rabbitmq
    hostname: rabbitmq
    
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    
    ports:
      - "5672:5672"
      - "15672:15672"
    
    networks:
      - taskflow-internal-network
    
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
  #---------------------------------------#

  identity-service.api:
    container_name: taskflow-identity-service
    hostname: identity-service.api
    
    build:
      context: ../..  
      dockerfile: Src/Services/Identity/TaskFlow.Identity.API/Dockerfile
    
    env_file:
      - .env
      - .env.identity-service
    
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - RabbitMqOptions__Port=5672
      - RabbitMqOptions__VirtualHost=/
      - RabbitMqOptions__HostName=rabbitmq
      - RabbitMqOptions__UserName=${RABBITMQ_USERNAME}
      - RabbitMqOptions__Password=${RABBITMQ_PASSWORD}
      - ConnectionStrings__SqlServerConnectionString=Server=${SQL_SERVER_HOST};Database=${SQL_SERVER_DB_NAME};User Id=${SQL_SERVER_USER};Password=${SQL_SERVER_PASSWORD};TrustServerCertificate=True;
    
    networks:
      - taskflow-internal-network
    
    depends_on:
      sqlserver:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped
  #---------------------------------------#

  tasks-service.api:
    container_name: taskflow-tasks-service
    hostname: tasks-service.api
    
    build:
      context: ../..
      dockerfile: Src/Services/Tasks/TaskFlow.Tasks.API/Dockerfile
    
    env_file:
      - .env
      - .env.tasks-service
    
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - RabbitMqOptions__Port=5672
      - RabbitMqOptions__VirtualHost=/
      - RabbitMqOptions__HostName=rabbitmq
      - RabbitMqOptions__UserName=${RABBITMQ_USERNAME}
      - RabbitMqOptions__Password=${RABBITMQ_PASSWORD}
      - ConnectionStrings__SqlServerConnectionString=Server=${SQL_SERVER_HOST};Database=${SQL_SERVER_DB_NAME};User Id=${SQL_SERVER_USER};Password=${SQL_SERVER_PASSWORD};TrustServerCertificate=True;
    
    networks:
      - taskflow-internal-network
    
    depends_on:
      sqlserver:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped
  #---------------------------------------#

  gateway:
    container_name: taskflow-gateway
    hostname: taskflow
    
    build:
      context: ../..
      dockerfile: Src/ApiGateway/TaskFlow.Gateway/Dockerfile
    
    env_file:
      - .env
      - .env.gateway
    
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    
    ports:
      - "5000:8080"
    
    networks:
      - taskflow-internal-network
    
    depends_on:
      - identity-service.api
      - tasks-service.api
    restart: unless-stopped
  #---------------------------------------#

volumes:
  sqlserver-data:
    