<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<PackageReference Include="Consul" />
		<PackageReference Include="Winton.Extensions.Configuration.Consul" />
		<PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\TaskFlow.Shared.Logging\TaskFlow.Shared.Logging.csproj" />
	</ItemGroup>

</Project>
