<Project Sdk="Microsoft.NET.Sdk">
	
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Http" />
    <PackageReference Include="NLog" />
    <PackageReference Include="NLog.Web.AspNetCore" />
  </ItemGroup>
	
  <ItemGroup>
    <ProjectReference Include="..\TaskFlow.Shared.Core\TaskFlow.Shared.Core.csproj" />
  </ItemGroup>
	
</Project>
