<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<PackageReference Include="NLog" />
		<PackageReference Include="NLog.Web.AspNetCore" />
		<PackageReference Include="Microsoft.AspNetCore.Http" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\TaskFlow.Shared.Core\TaskFlow.Shared.Core.csproj" />
	</ItemGroup>

</Project>
